<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="Gangireddy" failures="1" tests="1" name="Test" time="284598.355" errors="0" timestamp="2022-11-29T13:52:19 PST">
  <testcase classname="TestNGpackage.NewTestng" name="ball" time="284590.882">
    <failure type="java.lang.AssertionError" message="title displayes as expected expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: title displayes as expected expected [true] but found [false]
at TestNGpackage.NewTestng.ball(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- ball -->
  <testcase classname="TestNGpackage.NewTestng" name="testmethod" time="0.0">
    <ignored/>
  </testcase> <!-- testmethod -->
  <testcase classname="TestNGpackage.NewTestng" name="dog" time="0.0">
    <ignored/>
  </testcase> <!-- dog -->
  <testcase classname="TestNGpackage.NewTestng" name="apple" time="0.0">
    <ignored/>
  </testcase> <!-- apple -->
  <testcase classname="TestNGpackage.NewTestng" name="cat" time="0.0">
    <ignored/>
  </testcase> <!-- cat -->
</testsuite> <!-- Test -->
